### ISSUE TITLE
cant decode PC2 or AMS2 telemetry

### ISSUE THREAD

**Issue by goern** [ppatierno/formula1-telemetry#7]
Moin, I have been testing to receive telemetry from Project Cars 2 and AMS2, both configured to send PC2 data via UDP.

It results in an exception:
```
2021-08-14 23:06:52 WARN  NettyConsumer:214 - Closing channel as an exception was thrown from Netty. Caused by: [io.netty.handler.codec.DecoderException - java.lang.IndexOutOfBoundsException: readerIndex(1060) + length(4) exceeds writerIndex(1063): PooledUnsafeDirectByteBuf(ridx: 1060, widx: 1063, cap: 2048)]
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1060) + length(4) exceeds writerIndex(1063): PooledUnsafeDirectByteBuf(ridx: 1060, widx: 1063, cap: 2048)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1060) + length(4) exceeds writerIndex(1063): PooledUnsafeDirectByteBuf(ridx: 1060, widx: 1063, cap: 2048)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
        at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:818)
        at io.netty.buffer.ByteBuf.readFloatLE(ByteBuf.java:1540)
        at io.ppatierno.formula1.data.CarMotionData.fill(CarMotionData.java:44)
        at io.ppatierno.formula1.packets.PacketMotionData.fill(PacketMotionData.java:72)
        at io.ppatierno.formula1.PacketDecoder.decode(PacketDecoder.java:42)
        at io.ppatierno.formula1.PacketDecoder.decode(PacketDecoder.java:53)
        at io.ppatierno.formula1.PacketEventDecoder.decode(PacketEventDecoder.java:22)
        at io.ppatierno.formula1.PacketEventDecoder.decode(PacketEventDecoder.java:15)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 15 more
2021-08-14 23:06:52 WARN  NettyConsumer:214 - Closing channel as an exception was thrown from Netty. Caused by: [io.netty.handler.codec.DecoderException - java.lang.IndexOutOfBoundsException: readerIndex(556) + length(4) exceeds writerIndex(559): PooledUnsafeDirectByteBuf(ridx: 556, widx: 559, cap: 2048)]
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(556) + length(4) exceeds writerIndex(559): PooledUnsafeDirectByteBuf(ridx: 556, widx: 559, cap: 2048)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(556) + length(4) exceeds writerIndex(559): PooledUnsafeDirectByteBuf(ridx: 556, widx: 559, cap: 2048)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
        at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:818)
        at io.netty.buffer.ByteBuf.readFloatLE(ByteBuf.java:1540)
        at io.ppatierno.formula1.data.CarMotionData.fill(CarMotionData.java:56)
        at io.ppatierno.formula1.packets.PacketMotionData.fill(PacketMotionData.java:72)
        at io.ppatierno.formula1.PacketDecoder.decode(PacketDecoder.java:42)
        at io.ppatierno.formula1.PacketDecoder.decode(PacketDecoder.java:53)
        at io.ppatierno.formula1.PacketEventDecoder.decode(PacketEventDecoder.java:22)
        at io.ppatierno.formula1.PacketEventDecoder.decode(PacketEventDecoder.java:15)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 15 more
2021-08-14 23:06:52 INFO  Metadata:279 - [Producer clientId=raw-packets] Cluster ID: O3jU-ldsTeic9ytWhE-8SQ
2021-08-14 23:06:52 INFO  Metadata:279 - [Producer clientId=events] Cluster ID: O3jU-ldsTeic9ytWhE-8SQ
2021-08-14 23:06:52 INFO  Metadata:279 - [Producer clientId=drivers] Cluster ID: O3jU-ldsTeic9ytWhE-8SQ
```

**Comment by ppatierno** [comment]
Not sure what are you trying to do but this library is about decode/encode packets from/to Formula1 2020 game by Codemasters as the corresponding specification; it's not kind of general purpose for other games. I don't think they have same specification.
